# Generated by Django 4.1.7 on 2023-03-01 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baedal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='category',
            field=models.CharField(choices=[('치킨', '치킨'), ('중식', '중식'), ('한식', '한식')], max_length=50),
        ),
    ]
