# Generated by Django 4.1.7 on 2023-03-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baedal', '0002_alter_restaurant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('대기', '대기'), ('접수', '접수'), ('반려', '반려')], max_length=50),
        ),
    ]
